mybide_output/policy/views/auth_views.py
import pymysql

from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import check_password_hash
from werkzeug.utils import redirect

from policy import db
from policy.forms import UserCreateForm, UserLoginForm
# from policy.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')

def create_connection():
    db_database ="login"
    db_name ="admin"
    db_password ="wqend1001"
    db_url = "mybide.cutyxjtrt78p.us-east-1.rds.amazonaws.com"

    conn = pymysql.connect(host = db_url, user = db_name, passwd = db_password, db = db_database, port = 3306)
    cursor = conn.cursor()

    return conn, cursor


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()

    if request.method == 'POST' and form.validate_on_submit():
        conn, cursor = create_connection()

        sql = "select * from output_users where id = %s"
        cursor.execute(sql, form.username.data)
        check_validate = cursor.fetchall()
        print(check_validate)
        print(type(check_validate))

        if len(check_validate) == 0:
            print("error!!!")
            error = "존재하지 않는 사용자!!"
            flash(error)
        elif check_validate[0][1] != form.password.data:
            error = "잘못된 비밀번호 입니다!!"
            flash(error)
        else:
            print("good!!!")
            session.clear()
            session['user_id'] = form.username.data
            # return render_template('auth/signup.html')

            return redirect(url_for('main.index'))

    return render_template('auth/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = [session.get('user_id')]

    conn, cursor = create_connection()
    sql = "select * from output_users where id=%s"
    cursor.execute(sql, user_id)
    id_temp = cursor.fetchall()

    if user_id is None:
        g.user = None
    else:
        g.user = id_temp

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index')) # 수정

    
@bp.route('/signup/', methods=('GET', 'POST'))
def signup():

    form = UserCreateForm()
    conn, cursor = create_connection()

    # id, pwd, name, age, sex, address, create_date
    if request.method == 'POST' and form.validate_on_submit():
        sql = "select * from output_users where id=%s"
        cursor.execute(sql, form.id.data)
        check_validate = cursor.fetchall()

        if len(check_validate) == 0:
            # pwd = generate_password_hash(form.password1.data)
            temp = (form.id.data, form.password1.data, form.level.data, form.create_date)
            sql = "insert into output_users (id, pwd, lv, created_at ) values (%s,%s,%s,%s)"

            cursor.execute(sql, temp)
            conn.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')

    cursor.close()
    return render_template('auth/signup.html', form=form)

# ------------------------------------------------------

mybide_output/policy/views/img_gal.py
from policy.views.image_data import image
from flask import Blueprint,request,jsonify
from flask.templating import render_template
from pymongo import MongoClient
# from .app_id import search_image
from .pp import s3_image_path
from .hash_func import hashTag
from flask import Blueprint, url_for, render_template, flash, request, session

# from os import pipe, replace
# from warnings import showwarning
# from werkzeug.utils import redirect
# import os
# import re

bp = Blueprint('img_gallery', __name__, url_prefix='/image')
client = MongoClient('localhost', 27017)

@bp.route('/')
def home():
    return render_template('image_gal/gallery.html')
    
@bp.route('/gallery', methods=['POST'])
def post_articles():
    # 1. 검색 키워드 받기
    global url_receive
    
    url_receive = request.form['url_give'] # fix-it
    return jsonify({'result': 'success', 'msg': 'POST 연결되었습니다!'})


@bp.route('/gallery', methods=['GET'])
def read_articles():
    
    global url_receive # 검색 키워드 

    image_list = [] # 해시태그를 가진 사진들
    hash_tag = [] # 해당하는 사진의 해시태그들
    images_path = [] # 웹에 반환할 이미지

    all_image = s3_image_path() # user_image에 있는 모든 사진 list 가져오기
    #이미지 전체 리스트
    
    if url_receive is not None:
        # image_list = hashTag().search_pic_of_tag(url_receive) # 태그 포함된 이미지가 반환
        user_id = [session.get('user_id')]
        print('회원 아이디',user_id)

        search = url_receive # 검색어
        print(len(image_list))
        # image_list = search_image(user_id,search)
        image_list = ['1.jpg', '10.jpg', '11.jpg', '12.jpg', '13.jpg', '14.jpg', '15.jpg', '16.jpg', '17.jpg', '18.jpg', '19.jpg', '2.jpg', '20.jpg', '21.jpg', '22.jpg', '23.jpg', '24.jpg', '25.jpg', '26.jpg']
        print('검색어에 대한 리스트',image_list)

        print('S# 전체 데이터  \n\n',all_image)
        print('image타입',type(image_list))

    
    else:
        pass
    # 검색어 받음(str)

    for image_ in image_list:
        if image_ in all_image:
            images_path.append(image_)
            hash_tag.append(hashTag().show_all_hashtag(image_))

        
    print(images_path)
    print(image_list)
    return jsonify({'result': 'success', 'image_list':images_path,'hash_tag':hash_tag})

mybide_output/policy/templates/base.html
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!-- pybo CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Policy Server</title>
</head>
    {% include "navbar.html" %}

    {% block content %}
    {% endblock %}
    <!-- jQuery JS -->
    <script src="{{ url_for('static', filename='jquery-3.6.0.min.js') }}"></script>
    <!-- Bootstrap JS -->
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
    </body>
    </html>
</body>


</html>

mybide_output/policy/templates/form_errors.html
{% for field, errors in form.errors.items() %}
<div class="alert" role="alert"> 
    {{ form[field].label }}: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert" role="alert">
    {{ message }}
</div>
{% endfor %}

mybide_output/policy/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom" style="font-weight:bold" "margin-bottom: 0px;">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Policy</a> <!--수정-->
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">

        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('auth.signup') }}">회원가입</a>
            </li>
        </ul>
        
        {% if g.user %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
            </li>
        </ul>
        {% endif %}

        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('img_gallery.home') }}">SEARCH</a>
            </li>
        </ul>

    </div>
</nav>